name: siamese
channels:
  - defaults
  - pytorch
  - fastai
dependencies:
  - python>=3.7
  - pytorch=1.9.0
  - torchvision 
  - torchaudio 
  - cudatoolkit=10.2 
  - fastai=1.0.61
  - ipython=7.1.1
  - prompt_toolkit==2.0.10
  - notebook
  - jupyter
  - scikit-learn=0.24.2
  - pip
  - pip:
    - .